### ISSUE TITLE
Provides a simpler way to provide resource description information to facilitate resource creation when not using a visual interface

### ISSUE THREAD

**Issue by jpanda-cn** [catman-cc/catman-coder-workbench#6]

**Comment by jpanda-cn** [comment]
Referring to k8s resources, it should provide a simpler way to create resources in the form of APIs, rather than relying heavily on visual UI for operations.

e.g:
```yaml
  - kind: function
    namespace: xxx
    packageName: xxx
    name: xxx
    spec:
      args:
      - argA:
          type: string
          value: "hello"
          required: true
          default: "world"
      - argB:
          type: int
          value: 1
          required: false
          default: 2
      result:
        type: string
```
